name: Deploy to remote server
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 20.71.136.182
        username: will
        password: HighPavement92!
        port: 22
        script: | 
          cd /
          cd home
          cd will
          cd server
          git pull https://github.com/tokorv/server
